name: "release"
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: "Test"
        run: make test

      - name: "Build release"
        run: make release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/entropia-tracker-cli*
